// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppAPIKennzeichen.Data;

#nullable disable

namespace WebAppAPIKennzeichen.Migrations
{
    [DbContext(typeof(WebAppAPIKennzeichenContext))]
    partial class WebAppAPIKennzeichenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppAPIKennzeichen.Models.KennzeichenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bundesland")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kennzeichen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kreis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WappenLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KennzeichenInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
